services:
  neo4j:
    container_name: neo4j
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474" # HTTP
      - "7473:7473" # HTTPS
      - "7687:7687" # Bolt

